sudo: required

services:
  - docker

before_install:
  - docker build -t galklein/multi-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true galklein/multi-react-test npm run test -- --coverage

after_success:
  - docker build -t galklein/multi-client ./client
  - docker build -t galklein/multi-nginx ./nginx
  - docker build -t galklein/multi-api ./server
  - docker build -t galklein/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push galklein/multi-client
  - docker push galklein/multi-nginx
  - docker push galklein/multi-api
  - docker push galklein/multi-worker
###

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-776810786127"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
#WHAT is backet_path ?
